#!/usr/bin/ruby

require "date"
require "securerandom"

path = File.expand_path("source/posts")
date = Date.today.to_s

title = ARGV[0]
link  = title.downcase.gsub(/\W/, "-").gsub(/--+/,"-")

content = %Q{---
title: #{ARGV[0]}
date: #{date}
disqus: #{SecureRandom.uuid}
published: false
---

}

new_post = File.open("#{path}/#{date}-#{link}.html.md", "w")

new_post.write(content)
