#!/usr/bin/ruby

require "date"
require "securerandom"

path = File.expand_path("source/posts")
date = Date.today.to_s

title = ARGV[0]
link  = title.downcase.gsub(/\W/, "-").gsub(/--+/,"-")

content = %Q{---
title: #{ARGV[0]}
date: #{date}
disqus: #{SecureRandom.uuid}
published: false
---

}

file_path = "#{path}/#{date}-#{link}.html.md"

new_post = File.open(file_path, "w")

new_post.write(content)
puts "created file: #{file_path}"
